name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 48.217.68.0
          username: root
          password: Torikul131@Torikul131@
          script: |
            sudo bash -c 'cd /var/www/ecommerce-saas && ./deploy.sh'
